---
version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: daily
          timezone: America/New_York
      open-pull-requests-limit: 5
    - package-ecosystem: bundler
      directory: /
      schedule:
          interval: weekly
          timezone: America/New_York
      open-pull-requests-limit: 5
      allow:
          - dependency-type: all
