---
included:
    - Sources

# paths to ignore during linting. Takes precedence over `included`.
excluded:
    - Tests
    - Example
    - Carthage
    - ./*Tests
    - ./*UITests
    - ./Tests
    - ./*/*/*/*/main.swift # App Store Connect SDK structure
    - ./*/*/Tests # App Store Connect SDK structure

opt_in_rules:
    - array_init
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - empty_xctest_method
    - enum_case_associated_values_count
    - explicit_init
    - fallthrough
    - fatal_error_message
    - file_name
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - identical_operands
    - implicitly_unwrapped_optional
    - implicit_return
    - joined_default_parameter
    - last_where
    - legacy_multiple
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - modifier_order
    - nimble_operator
    - nslocalizedstring_key
    - nslocalizedstring_require_bundle
    - object_literal
    - operator_usage_whitespace
    - optional_enum_case_matching
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - prohibited_interface_builder
    - prohibited_super_call
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - reduce_into
    - redundant_nil_coalescing
    - redundant_type_annotation
    - sorted_first_last
    - static_operator
    - strong_iboutlet
    - switch_case_on_newline
    - test_case_accessibility
    - toggle_bool
    - trailing_whitespace
    - type_contents_order
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - untyped_error_in_catch
    - unused_capture_list
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - yoda_condition

analyzer_rules:
    - unused_declaration
    - unused_import

vertical_whitespace:
    max_empty_lines: 2

function_body_length: 200

cyclomatic_complexity:
    warning: 3 # Two nested ifs are acceptable
    error: 4 # 4 nested ifs shows warning, 5 causes compile error

type_body_length:
    error: 400

type_name:
    allowed_symbols: [_] # these are allowed in type names

identifier_name:
    excluded:
        - id
        - URL

file_length: 1000

reporter: json

custom_rules:
    force_https:
        name: Force HTTPS over HTTP
        regex: ((?i)http(?!s))
        match_kinds: string
        message: HTTPS should be favored over HTTP
        severity: warning

type_contents_order:
    order:
        - case
        - type_alias
        - associated_type
        - ib_outlet
        - ib_inspectable
        - subtype
        - [type_property, instance_property]
        - [initializer, type_method, view_life_cycle_method, subscript, other_method, ib_action]

modifier_order:
    preferred_modifier_order:
        - [acl, override, setterACL, dynamic, mutators, lazy, final, required, convenience, typeMethods, owned]

conditional_returns_on_newline:
    if_only: true
