os: osx
osx_image: xcode11.2
language: swift
rvm: 2.6.1

addons:
  homebrew:
    brewfile: true
    update: true

cache:
  bundler: true
  directories:
    - $HOME/.rvm/

branches:
  only:
    - master
    - develop
  except:
    - "/^[^\\/]+\\/\\d+(?:\\.\\d+)+\\/\\d+$/"

env:
   global:
     - PROJECT_NAME="MobileCI"
     - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - make setup

jobs:
  include:
    - &test
      stage: test
      name: iPhone Pro tests
      env:
        - LANE="test_iphone_pro"
        - CACHE_SWIFT_VERSION="MobileCI"
      before_script:
        - bundle exec danger
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - "./cc-test-reporter before-build"
      script:
        - bundle exec fastlane "$LANE"
      after_success:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

    - <<: *test
      name: iPad
      env: LANE="test_ipad"
      if: (commit_message =~ /(@test ipad)/)

    - stage: carthage
      name: Carthage build
      if: "commit_message =~ /^(\\[#Carthage|\\[\\#Release)/"
      script: carthage build --no-skip-current --configuration Release

stages:
  - test
  - carthage
