version: 2.1
orbs:
  ios: kevnm67/ios-pipelines@dev:alpha
  slack: circleci/slack@4.2.0

ios_contexts: &ios_contexts [iOS, slack]

install_dependencies: &install_dependencies
    pretest_steps:
        - run: |
            make setup

run_tests: &run_tests
    ios/test:
        name: test
        context: *ios_contexts
        with_spm: true
        lane: test_iphone_pro
        cc_prefix: >
            format-coverage ./fastlane/test_output/cobertura.xml -t cobertura -d;./cc-test-reporter upload-coverage
        <<: *install_dependencies
        post-steps:
          - slack/notify:
                event: fail
                template: basic_fail_1
        requires: [prepare]

branch_filters: &branch_filters [master, main, development, /^hotfix.*/, /^release\/.*/]

deploy_filters: &deploy_filters
    branches:
        only: *branch_filters
    tags:
        only: /.*/

#############
# workflows #
#############
workflows:
    build-and-test:
        jobs:
            - ios/run_with_setup:
                  name: prepare
                  context: *ios_contexts
                  scripts:
                      - run: bundle exec danger
                  filters:
                      branches:
                          ignore: *branch_filters

            - <<: *run_tests

    build-test-deploy:
        jobs:
            - ios/run_with_setup:
                  name: prepare
                  context: *ios_contexts
                  filters:
                      branches:
                          only: *branch_filters

            - <<: *run_tests

            - slack/on-hold:
                  channel: ios-builds
                  context: *ios_contexts
                  requires: [test]
                  filters: *deploy_filters