version: 2.1
orbs:
  kjm-dev: kjm-dev/ios-pipelines@dev:first

defaults: &defaults
  macos:
    xcode: '11.2.1'
  working_directory: /Users/distiller/MobileCI
  shell: /bin/bash --login -o pipefail
  environment:
    PROJECT_NAME: "MobileCI"
    CIRCLE_ARTIFACTS: /tmp/$PROJECT_NAME-artifacts
    CIRCLE_TEST_REPORTS: /tmp/$PROJECT_NAME-test-results
    LC_ALL: en_US.UTF-8
    BUNDLE_PATH: vendor/bundle
    FL_OUTPUT_DIR: /Users/distiller/$PROJECT_NAME/fastlane

jobs:
  test:
    <<: *defaults
    description: Run tests
    steps:
      - checkout
      - kjm-dev/danger
      - run:
          name: Setup build environment
          command: |
            make setup
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - kjm-dev/lane:
          named: test_iphone_pro
      - run:
          name: Upload test results
          command: |
            ./cc-test-reporter after-build
      - store_test_results:
          path: /Users/distiller/$PROJECT_NAME/test_output

workflows:
  build-and-test:
    jobs:
      - test
