version: 2.1
orbs:
  ios-quality-checks: storytel/ios-quality-checks@0.0.1
  danger: ngs/danger@0.0.1
  kjm-dev: kjm-dev/ios-pipelines@dev:first
  fastlane: ngs/fastlane@0.0.3

jobs:
  danger:
    executor: kjm-dev/v11-1
    description: Run danger-swift
    steps:
      - kjm-dev/danger:

  test:
    description: Run tests
    executor: kjm-dev/v11-1
    steps:
      - kjm-dev/bundle-install:
          bundle_path: 'vendor/bundler'
      - kjm-dev/lane:
          named: test_iphone_x

workflows:
  build-and-test:
    jobs:
      - danger
      - test
