version: 2.1
orbs:
  kjm-dev: kjm-dev/ios-pipelines@dev:first

defaults: &defaults
  macos:
    xcode: '11.1.0'
  working_directory: /Users/distiller/CircleCI
  shell: /bin/bash --login -o pipefail
  environment:
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    LC_ALL: en_US.UTF-8
    BUNDLE_PATH: vendor/bundle
    FL_OUTPUT_DIR: /Users/distiller/CircleCI/fastlane

jobs:
  danger:
    <<: *defaults
    description: Run danger-swift
    steps:
      - checkout
      - kjm-dev/danger

  test:
    <<: *defaults
    description: Run tests
    steps:
      - checkout
      - kjm-dev/danger
      - run:
          name: Install Rome
          command: brew install blender/homebrew-tap/rome
      - kjm-dev/lane:
          named: carthage_ci
      - kjm-dev/lane:
          named: test_iphone_x

workflows:
  build-and-test:
    jobs:
      - test
