version: 2.1
orbs:
  kjm-dev: kjm-dev/ios-pipelines@dev:first

defaults: &defaults
  macos:
    xcode: '11.2.0'
  working_directory: /Users/distiller/MobileCI
  shell: /bin/bash --login -o pipefail
  environment:
    CIRCLE_ARTIFACTS: /tmp/MobileCI-artifacts
    CIRCLE_TEST_REPORTS: /tmp/MobileCI-test-results
    LC_ALL: en_US.UTF-8
    BUNDLE_PATH: vendor/bundle
    FL_OUTPUT_DIR: /Users/distiller/MobileCI/fastlane

jobs:
  danger:
    <<: *defaults
    description: Run danger-swift
    steps:
      - checkout
      - kjm-dev/danger

  test:
    <<: *defaults
    description: Run tests
    steps:
      - checkout
      - kjm-dev/danger
      - run:
          name: Install Rome
          command: brew install blender/homebrew-tap/rome
      - kjm-dev/lane:
          named: carthage_ci
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - kjm-dev/lane:
          named: test_iphone_pro
      - run:
          name: Upload test results
          command: |
            ./cc-test-reporter after-build

workflows:
  build-and-test:
    jobs:
      - test
