---
name: Codeowners merging
on:
    pull_request_target: {types: opened}
    issue_comment: {types: created}
    pull_request_review: {types: submitted}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Run Codeowners merge check
              uses: orta/code-owner-self-merge@1.5.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
