---
name: Release Drafter
on:
    push:
        branches:
            - main
            - $default-branch
            - v.+
        # pull_request event is required only for autolabeler
        pull_request:
            # Only following types are handled by the action or use all.
            types: [opened, reopened, synchronize]

jobs:
    update_release_draft:
        runs-on: ubuntu-latest
        steps:
            - uses: release-drafter/release-drafter@v5.15.0
              with:
                  config-name: release_drafter.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
