name: rultor
"on": pull_request_review
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Rultor
        uses: g4s8/rultor-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
